Company.find_or_create_by(key: "swedishorphan", nn_id: "36316", name: "Swedish Orphan Biovitrum publ AB ")
Company.find_or_create_by(key: "kungsleden", nn_id: "3546", name: "Kungsleden AB")
Company.find_or_create_by(key: "fingerprint", nn_id: "4870", name: "Fingerprint Cards AB-B")
Company.find_or_create_by(key: "arcam", nn_id: "88584", name: "Arcam  AB")
Company.find_or_create_by(key: "alfa-laval", nn_id: "18634", name: "Alfa Laval AB")
Company.find_or_create_by(key: "ericsson", nn_id: "101", name: "Ericsson")
Company.find_or_create_by(key: "ncc", nn_id: "837", name: "NCC AB")
Company.find_or_create_by(key: "lindab", nn_id: "37400", name: "Lindab International AB")
Company.find_or_create_by(key: "intrum", nn_id: "18962", name: "Intrum Justitia AB")
Company.find_or_create_by(key: "svenska", nn_id: "341", name: "Svenska Handelsbanken AB")
Company.find_or_create_by(key: "elekta", nn_id: "806", name: "Elekta AB-B SHS")
Company.find_or_create_by(key: "hexpol", nn_id: "55907", name: "Hexpol AB")
Company.find_or_create_by(key: "sas", nn_id: "13557", name: "SAS AB")
Company.find_or_create_by(key: "jm", nn_id: "13217", name: "JM AB")
Company.find_or_create_by(key: "modern", nn_id: "3598", name: "Modern Times Group MTG AB")
Company.find_or_create_by(key: "com", nn_id: "101281", name: "COM HEM Holding AB")
Company.find_or_create_by(key: "unibet", nn_id: "36950", name: "Unibet Group PLC ")
Company.find_or_create_by(key: "getinge", nn_id: "812", name: "Getinge AB")
Company.find_or_create_by(key: "moberg", nn_id: "79252", name: "Moberg Pharma AB")
Company.find_or_create_by(key: "castellum", nn_id: "966", name: "Castellum AB ")
Company.find_or_create_by(key: "mycronic", nn_id: "4714", name: "Mycronic AB")
Company.find_or_create_by(key: "tele2", nn_id: "1027", name: "Tele2 AB")
Company.find_or_create_by(key: "africa", nn_id: "77948", name: "Africa Oil Corp")
Company.find_or_create_by(key: "new", nn_id: "920", name: "New Wave Group AB")
Company.find_or_create_by(key: "millicom", nn_id: "24507", name: "Millicom International Cellular S.A.")
Company.find_or_create_by(key: "h&m", nn_id: "992", name: "H & M Hennes & Mauritz AB")
Company.find_or_create_by(key: "oriflame", nn_id: "110536", name: "Oriflame Holding AG")
Company.find_or_create_by(key: "mekonomen", nn_id: "4986", name: "Mekonomen AB")
Company.find_or_create_by(key: "betsson", nn_id: "5121", name: "Betsson AB")
Company.find_or_create_by(key: "meda", nn_id: "-", name: "MEDA AB")
Company.find_or_create_by(key: "byggmax", nn_id: "75712", name: "Byggmax Group AB")
Company.find_or_create_by(key: "billerud", nn_id: "14922", name: "Billerud AB")
Company.find_or_create_by(key: "qliro", nn_id: "79303", name: "Qliro Group AB")
Company.find_or_create_by(key: "skf", nn_id: "285", name: "SKF AB")
Company.find_or_create_by(key: "mq", nn_id: "76085", name: "MQ Holding AB")
Company.find_or_create_by(key: "skanska", nn_id: "283", name: "Skanska AB")
Company.find_or_create_by(key: "bulten", nn_id: "82239", name: "Bulten AB")
Company.find_or_create_by(key: "boliden", nn_id: "15285", name: "Boliden AB ")
Company.find_or_create_by(key: "haldex", nn_id: "817", name: "Haldex AB")
Company.find_or_create_by(key: "ssab", nn_id: "301", name: "SSAB AB")
Company.find_or_create_by(key: "lundin", nn_id: "22335", name: "Lundin Petroleum AB")
Company.find_or_create_by(key: "ica", nn_id: "32443", name: "ICA Gruppen AB")
Company.find_or_create_by(key: "avanza", nn_id: "988", name: "Avanza Bank Holding AB")
Company.find_or_create_by(key: "sandvik", nn_id: "4928", name: "Sandvik AB")
Company.find_or_create_by(key: "nordnet", nn_id: "4872", name: "Nordnet AB")
Company.find_or_create_by(key: "net", nn_id: "3871", name: "Net Insight AB")
Company.find_or_create_by(key: "swedishmatch", nn_id: "361", name: "Swedish Match AB")
Company.find_or_create_by(key: "granges", nn_id: "103110", name: "Granges AB")
Company.find_or_create_by(key: "securitas", nn_id: "401", name: "Securitas AB")
Company.find_or_create_by(key: "volvo", nn_id: "366", name: "VOLVO AB")
Company.find_or_create_by(key: "alimak", nn_id: "110204", name: "Alimak Group AB")
Company.find_or_create_by(key: "axfood", nn_id: "4590", name: "AXFOOD AB")
Company.find_or_create_by(key: "tethys", nn_id: "24588", name: "Tethys Oil AB")
Company.find_or_create_by(key: "infant", nn_id: "120381", name: "Infant Bacterial Therapeutics")
Company.find_or_create_by(key: "eniro", nn_id: "11046", name: "Eniro AB")
Company.find_or_create_by(key: "hemfosa", nn_id: "100152", name: "Hemfosa Fastigheter AB")
Company.find_or_create_by(key: "aak", nn_id: "36273", name: "AAK AB")
Company.find_or_create_by(key: "atlas", nn_id: "46", name: "Atlas Copco AB (publ)")
Company.find_or_create_by(key: "hexagon", nn_id: "819", name: "Hexagon AB")
Company.find_or_create_by(key: "netent", nn_id: "62494", name: "Netent AB")
Company.find_or_create_by(key: "dustin", nn_id: "106202", name: "Dustin Group AB")
Company.find_or_create_by(key: "sensys", nn_id: "12241", name: "Sensys Gatso Group AB")
Company.find_or_create_by(key: "kambi", nn_id: "101199", name: "Kambi Group ORD")
Company.find_or_create_by(key: "ratos", nn_id: "94883", name: "Ratos AB")
Company.find_or_create_by(key: "proffice", nn_id: "-", name: "Proffice AB")
Company.find_or_create_by(key: "indutrade", nn_id: "31308", name: "Indutrade AB")
Company.find_or_create_by(key: "industrivärden", nn_id: "143", name: "Industrivärden AB")
Company.find_or_create_by(key: "precise", nn_id: "10751", name: "Precise Biometrics AB")
Company.find_or_create_by(key: "vostok", nn_id: "110742", name: "Vostok Emerging Market Finance LTD")
Company.find_or_create_by(key: "teliasonera", nn_id: "5095", name: "TeliaSonera AB")
Company.find_or_create_by(key: "trelleborg", nn_id: "364", name: "Trelleborg AB")
Company.find_or_create_by(key: "tribona", nn_id: "-", name: "Tribona AB")
Company.find_or_create_by(key: "husqvarna", nn_id: "34915", name: "Husqvarna AB")
Company.find_or_create_by(key: "kappahl", nn_id: "33359", name: "Kappahl AB")
Company.find_or_create_by(key: "concentric", nn_id: "82656", name: "Concentric AB")
Company.find_or_create_by(key: "evolution", nn_id: "107867", name: "Evolution Gaming Group")
Company.find_or_create_by(key: "active", nn_id: "877", name: "Active Biotech AB")
Company.find_or_create_by(key: "dannemora", nn_id: "-", name: "Dannemora mineral  AB")
Company.find_or_create_by(key: "wihlborgs", nn_id: "29759", name: "Wihlborgs Fastigheter AB")
Company.find_or_create_by(key: "aerocrine", nn_id: "-", name: "Aerocrine AB")
Company.find_or_create_by(key: "orexo", nn_id: "31885", name: "Orexo AB")
Company.find_or_create_by(key: "transmode", nn_id: "-", name: "Transmode AB")
Company.find_or_create_by(key: "sanitec", nn_id: "-", name: "Sanitec Corporation")
Company.find_or_create_by(key: "cloetta", nn_id: "63225", name: "Cloetta")
Company.find_or_create_by(key: "medivir", nn_id: "1020", name: "Medivir AB")
Company.find_or_create_by(key: "electrolux", nn_id: "81", name: "Electrolux AB")
Company.find_or_create_by(key: "axis", nn_id: "5150", name: "Axis Communcations AB")
Company.find_or_create_by(key: "bufab", nn_id: "99667", name: "Bufab AB")
Company.find_or_create_by(key: "seamless", nn_id: "34601", name: "Seamless Distribution AB")
Company.find_or_create_by(key: "opus", nn_id: "35920", name: "Opus GROUP")
Company.find_or_create_by(key: "be", nn_id: "37309", name: "BE Group")
Company.find_or_create_by(key: "nobia", nn_id: "19095", name: "Nobia AB")
Company.find_or_create_by(key: "episurf", nn_id: "78419", name: "Episurf Medical ")
Company.find_or_create_by(key: "holmen", nn_id: "222", name: "Holmen AB")
Company.find_or_create_by(key: "hyresfastighetsfonden", nn_id: "-", name: "Hyresfastighetsfonden Management")
Company.find_or_create_by(key: "i.a.r", nn_id: "2346", name: "I.A.R Systems Group AB")
Company.find_or_create_by(key: "cortus", nn_id: "27960", name: "Cortus Energy AB ")
Company.find_or_create_by(key: "clas", nn_id: "4145", name: "Clas Ohlson AB")
Company.find_or_create_by(key: "saab", nn_id: "1051", name: "SAAB AB")
Company.find_or_create_by(key: "alliance", nn_id: "-", name: "Alliance Oil Company Ltd")
Company.find_or_create_by(key: "black", nn_id: "66922", name: "Black Earth Farming ")
Company.find_or_create_by(key: "pa", nn_id: "-", name: "PA Resources AB")
Company.find_or_create_by(key: "sca", nn_id: "323", name: "SCA AB")
